### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by HAYASHI0884** [HAYASHI0884/protospace-31115#1]
# URL
https://protospace-31115.herokuapp.com/
宜しくお願い致します。

**Comment by Nishi0418** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
・未ログイン状態だと、商品一覧ページに遷移されない。
・上記URLからアクセスすると、ログイン画面に遷移する。
・商品詳細からユーザーにアクセスすると、常に林さんのユーザー情報が表示される。

修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by HAYASHI0884** [comment]
遅くなり、申し訳ございません。
修正完了いたしましたので、ご確認のほど宜しくお願い致します。

**Comment by Nishi0418** [comment]
林さん
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

別途、最終課題の案内をチャンネルの方に送信させて頂きます。
今しばらくお待ちください。

**Comment by HAYASHI0884** [comment]
ありがとうございます！
承知いたしました。これから最終課題に入らせていただきます。
